### ISSUE TITLE
Make it automatically connect to the internet on boot and download the latest data nodes

### ISSUE THREAD

**Issue by jason0597** [zoogie/seedminer#12]

**Comment by zoogie** [comment]
This will be added on 2.1

**Comment by Valeri0p** [comment]
Also, you cloud add a function to send the generated msed_data to a server automatically ;)

**Comment by jason0597** [comment]
yes but what server? @Valeri0p

**Comment by zoogie** [comment]
Ok, this is implemented but not automatically. But it's easy enough.
seedminer_launcher.py update-db
that's it.
