### ISSUE TITLE
readme.txt - After Tadpole

### ISSUE THREAD

**Issue by greenDarkness** [zoogie/seedminer#13]
Hello there, I have a suggestion and a question for the seedminer readme.
For 2), would it be possible to list the steps to "Import it"?
```
2) Import it, and you should have dsiwarehax execution.
```
For 3) did you mean to link to this page instead? https://3ds.hacks.guide/installing-boot9strap-(dsiware-save-injection)
```
3) Go to https://3ds.guide/installing-boot9strap-(dsiware-game-injection) and continue at section V.
```
Thank you for taking the time to read this, and for all your work with Seedminer.

**Comment by zoogie** [comment]
2) I think this is assumed knowledge. I mean, it's just: tap on the app, confirm dialogs. The readme is wordy enough without remedial basic usage tutorials added. I may add some words, but it will be brief.
3) the site properly redirects with that link I give but I'll change it anyway.

**Comment by greenDarkness** [comment]
2. Do you mean tap on the app from the home screen? Or another screen? To be honest I'm not sure of how to import saves without a 3rd party device (unless there's a prompt upon launching the game). Thanks so much.

3. Again, thank you!
