### ISSUE TITLE
seedminer_launcher: allow custom file name for movable_part1.sed in id0 method

### ISSUE THREAD

**Issue by figgyc** [zoogie/seedminer#14]
Would make it way easier to add id0s in bulk

**Comment by zoogie** [comment]
This is too niche to clutter the options even more.

But this should be a really easy thing to add yourself
https://github.com/zoogie/seedminer/blob/master/seedminer/seedminer_launcher.py#L242 and
https://github.com/zoogie/seedminer/blob/master/seedminer/seedminer_launcher.py#L281
```
with open("movable_part1.sed", "rb") as f: -->
with open(sys.argv[3], "rb") as f:
```
Then:
seedminer_launcher.py id0 abc234342342fdaa...  movable_somethingelse.sed
that should do it.
