### ISSUE TITLE
Support for Geforce x50 or less cards?

### ISSUE THREAD

**Issue by HolidayOugi** [zoogie/seedminer#16]
https://gbatemp.net/threads/seedminer-single-system-dsiware-injection.495685/page-65 It seems like it gives an "out of resources error" when trying to bruteforce with those gpus.

I'm not the original commentator but I've tried it myself on a Geforce 650 and a Geforce 930M gpu and it's replicable.

**Comment by zoogie** [comment]
This is a bfcl issue, which I didn't write. Wouldn't even know where to begin fixing anything with that project.
https://github.com/Jimmy-Z/bfCL

**Comment by Mike15678** [comment]
This has been fixed with #29 which has now been merged

**Comment by piratesephiroth** [comment]
nice, it's unfortunate that update 11.8 pretty much killed seedminer though

**Comment by zoogie** [comment]
@piratesephiroth 
Try again lol
https://cdn.discordapp.com/attachments/441119928334942218/476510256382476309/chart10.png
