### ISSUE TITLE
where to post msed data

### ISSUE THREAD

**Issue by YYoshi241** [zoogie/seedminer#18]
If we would like to post our msed data to improve seedminer, where would we post it?
A url in the comments would help as well as the readme.

**Comment by jason0597** [comment]
so far it's been on gbatemp, [this thread](https://gbatemp.net/threads/seedminer-single-system-dsiware-injection.495685/) specifically

**Comment by YYoshi241** [comment]
thanks 
I uploaded mine there (obviously since I asked)
thanks @zoogie for making this :)
