### ISSUE TITLE
[Request] move from a movable_part1.sed format to a text format

### ISSUE THREAD

**Issue by jason0597** [zoogie/seedminer#20]
Currently, if you want to add your ID0 to your movable_part1 file, you have to either use the python script or use a hex editor.

A lot of people probably download python just to do this step, only to immediately send their movable_part1.sed file to someone else for mining. They didn't really need python, it's just another big download that they needed only for one tiny step.
The ID0 is just a string of characters. If movable_part1 was a text file instead (perhaps also add a `.txt` extension at the end to indicate this to people), you could simply use your preinstalled text editor to add in the ID0 string, without having to download either python or a hex editor.
What I would suggest is having it so that a new standard is created, which is easy to work with (even with non-computer savvy users)

![img](https://i.imgur.com/HvQ9pa7.png)

Just hardcode the lines 2 and 8 in the code, and parse the characters into numbers/byte arrays.

I understand that this change would require pretty deep edits in both seedstarter and seedminer, and it would certainly create at least some kind of reaction from the community, but it's for the best

I may be able to help with the seedstarter edits, but I am not experienced with python so I can't really help with seedminer.

**Comment by zoogie** [comment]
I have a plan for making seedminer a little more noob friendly. I don't think bin->text would help in that case.

**Comment by jason0597** [comment]
what kind of plan are we talking about?

**Comment by zoogie** [comment]
Text based menu gui. Removal of command line stuff. Avoid installing python.
That's what trips most people up from what I see.

Please don't suggest Java for the GUI . I won't go in that direction.

**Comment by jason0597** [comment]
is this going to be based on ncurses?

**Comment by zoogie** [comment]
No, lol, I avoid libraries when I can. A simple menu is not hard to code.

**Comment by jason0597** [comment]
one last question: how are you going to avoid installing python?

**Comment by zoogie** [comment]
pyinstaller. I don't like the huge exe's or false virus positives but Python is what I'm comfortable with.

**Comment by zacchi4k** [comment]
@zoogie so are other options, like Qt and Mono, out of the question too?
