### ISSUE TITLE
[RESOLVED] no module named Cryptodome.Cipher

### ISSUE THREAD

**Issue by babeuseu** [zoogie/seedminer#21]
When I launch the script python gives me this error.
I tried installing crypto pycrypto it still wont work.

MII selected
Traceback (most recent call last):
  File "seedminer_launcher.py", line 394, in <module>
    mii_gpu()
  File "seedminer_launcher.py", line 85, in mii_gpu
    from Cryptodome.Cipher import AES
ImportError: No module named Cryptodome.Cipher

**Comment by zoogie** [comment]
pip install pycryptodomex

**Comment by babeuseu** [comment]
thank you very much sir
