### ISSUE TITLE
[Request] Upload msed data using python script

### ISSUE THREAD

**Issue by PixelSergey** [zoogie/seedminer#22]
It's quite time-consuming to upload the data to a gbatemp thread (especially without a gbatemp account) (especially if you mine for many people). It would be handy to have a feature to simply type `python3 seedminer_launcher3.py upload` to upload and delete the existing msed data in the working directory.

**Comment by jason0597** [comment]
nearly everybody uses the Jenkins DIS, and that automatically calculates the msed_data given a movable.sed 
it then uploads the msed_data to a secret repository where zoogie can retrieve it

**Comment by PixelSergey** [comment]
Huh, didn't know. Guess this has no use then

**Comment by PixelSergey** [comment]
Huh, didn't know. Guess this has no use then
