### ISSUE TITLE
feature request: add check for movable.sed at the end of gpu mining

### ISSUE THREAD

**Issue by lorilith** [zoogie/seedminer#25]
Currently, if bfcl fails to run there is no error message displayed, the script just ends
Adding either error message display or checking for completion of the mining would alleviate some issues people have with "i only have a part1 and part2"

**Comment by zoogie** [comment]
Noted. I'll look into it before the next version is put out.

**Comment by Resaec** [comment]
Im not sure if this is related, but it is also a breaking bug:
This is part of the output I get when starting to mine a moveable_part1.sed using gpu on current commit
`py -3 .\seedminer_launcher3.py gpu`

> bfcl msky XXX YYY 00000000 00400000
> invalid parameters

This is the same output on the latest released binary

> bfcl msky XXX YYY 00000000

XXX and YYY are the same on both versions, truncated for privacy?
It seems like bfcl does not expect to get 5 parameters.
All output on Windows 10
