### ISSUE TITLE
Raspberry Pi GPU Support

### ISSUE THREAD

**Issue by elaine-jackson** [zoogie/seedminer#26]
The Raspberry Pi 3 Model B has a ) 1.2 GHZ quad-core ARM Cortex A53 (ARMv8 Instruction Set) CPU and a Broadcom VideoCore IV @ 400 MHz GPU. Would it be possible to get support for this GPU? Would it even be practical. This issue is just to raise the question - I'm fully aware it'd be very slow.

**Comment by zoogie** [comment]
This would be worse than integrated graphics on PC so not worth the time.
