### ISSUE TITLE
Seed miner 

### ISSUE THREAD

**Issue by Terminatorali** [zoogie/seedminer#27]
The download link for seed miner is not downloading i already have everything only that is Left even the starter pack downloaded plz help

**Comment by jason0597** [comment]
can you tell us which download link you are trying to use?

**Comment by jason0597** [comment]
also, what starter pack are you referring to?

**Comment by Terminatorali** [comment]
I have the starter pack its a mega link

**Comment by Terminatorali** [comment]
https://mega.nz/#!BZo3EATI!3tfHZbT3pXziLDJn8IOlvzL-V4Zd_fR6tlQdMWVu7uc

**Comment by jason0597** [comment]
where did you get it from? what guide are you following?

also, i would recommend you to not use the github issues as a main method for support, github issues are for recommending suggestions to improve the piece of software itself, or to report bugs
it is recommended that you join the discord server above, you can find me there (jason0597)

**Comment by zoogie** [comment]
Don't do video guides, instead:
https://3ds.hacks.guide
https://github.com/zoogie/seedminer/releases/latest
