### ISSUE TITLE
endianness

### ISSUE THREAD

**Issue by parrotgeek1** [zoogie/seedminer#3]
This won't work right on big endian systems  because you don't do any conversion

**Comment by zoogie** [comment]
https://en.wikipedia.org/wiki/Endianness#Current_architectures

>The few current big-endian architectures include the IBM z/Architecture, Freescale ColdFire (which is Motorola 68000 series-based), Xilinx Microblaze, SuperH, Atmel AVR32.

lol, gotta look out for that .00001% of the market :-P
You're not wrong, but I don't think this is worthy of concern.

**Comment by parrotgeek1** [comment]
Alright. I was just being overly careful.

FYI it's not uncommon, there are a lot of mips big endian wifi router SoCs because it's more efficient that way (network order is already big endian)
