### ISSUE TITLE
bfcl invalid argument

### ISSUE THREAD

**Issue by Resaec** [zoogie/seedminer#31]
When using the current commit to bruteforce a moveable_part1.sed I get this output after successfully generating part2
`py -3 .\seedminer_launcher3.py gpu`

 > bfcl msky XXX YYY 00000000 00400000
 > invalid parameters

This is the output on the latest released binary package

 > bfcl msky XXX YYY 00000000

XXX and YYY are the same on both versions, truncated for privacy?
It seems like bfcl does not expect to get 5 parameters.
All output on Windows 10

**Comment by zoogie** [comment]
The latest commit has a bunch of extra features added mainly for the benefit of people who mine for the automated service at:
https://bruteforcemovable.com/

The latest release package is what's intended for general users.

**Comment by Mike15678** [comment]
It would seem that the bfCL submodule on the master branch is not updated from the latest commit on zoogie’s bfCL repo anymore which could explain why bfCL is outputting an error (assuming you compiled the now outdated submodule).

**Comment by Resaec** [comment]
Thats it, a current binary works fine
