### ISSUE TITLE
Job reached the specified max offset and was killed...

### ISSUE THREAD

**Issue by kategray** [zoogie/seedminer#35]
I'm leaving a node open as a volunteer, and getting a fair number of terminations due to reaching max offset.

They look like:

```
Downloading part1 for device 01d5dd9a44452d0935a661e7733a6f74
Bruteforcing 2021-04-20 15:47:23.586577
old3ds detected
Distance: 000000A0
Set MaxOffset to: 28
GPU selected
Old3DS msed - this can happen on a New3DS
LFCS      : 0xXXXXXX
msed3 est : 0xXXXXXX
Error est : -124
ID0 hash 0: f68909024821cb75ab2f19269c830bf6
Hash total: 1
movable_part2.sed generation success
bfcl msky c12f4a000000000000000000d5d60e00 f68909024821cb75ab2f19269c830bf6 00000000 38000000
selected device NVIDIA GeForce RTX 3090 on platform NVIDIA CUDA
0.008 seconds for OpenCL compiling
local work size: 256
33.10 seconds, 7265.93 M/s
Max offset reached! Brute-forcing will now terminate!
```

Looking in the launcher python script, it states "16384 should be considered the max though!".  

Is there a reason for this particular limit, or would raising that limit actually help?  I'm generally done between half a second and 3.5 seconds, so I don't mind taking a bit longer.

**Comment by deadphoenix8091** [comment]
The maxoffset is chosen based on how close datapoints we have are to the datapoint we are trying to bruteforce. The maxoffset steps are not choosen at random but were calculated mathematically to ensure that we dont abort prematurely. 

These aborted jobs are likely due to invalid id0 being provided by the user. You can increase the maxoffset but that likely wont increase your hitrate.

**Comment by kategray** [comment]
Makes sense.  Thank you for the explanation

I've increased the offset, and so far I haven't seen any failures.  When I get a few minutes, I'll put some code in that tells me if it would have aborted but succeeded with the increased offset.  If I don't get any in a couple days, I'll put it back.

**Comment by zoogie** [comment]
Did you set up your seedminer node to download the latest msed data? (this is a pre-approximation of the bruteforce based on previous successful mines - it greatly helps bruteforce speed).
https://github.com/zoogie/nodes

That might have been why you were getting maxoffset aborts but most likely what Deadphoenix said is the reason. 

Anyway, I've updated the latest release on this repo to match Deadphoenix's fork (most used version) and updated the msed data included within.

(off topic but holy shit @ that monster GPU hash speed!)

**Comment by kategray** [comment]
It’s a 3090.  The increased offset seemed to work.
