### ISSUE TITLE
Movable.Sed share

### ISSUE THREAD

**Issue by ImYourBoyRoy** [zoogie/seedminer#5]
Reading your 34⅕C3 : EOL IS LOL - you stated that you needed donations of the movable.sed.  I am interested in assisting with this, with a single concern of being restricted any online use of my 3ds by potential misuse of this share.  (Assuming someone with malicious intent were to get a hold of it...such as a banned console...or even nintendo and their ban lists).  Could you please share with me the "worst case scenario" as well as your preferred method of sharing?

Thank you for all of your work.  I think this is fantastic that there are people developing on this awesome platform.

**Comment by zoogie** [comment]
You're not sharing the movable.sed itself, you share the msed_data.
Read the OP here, it describes what is actually being shared.
https://gbatemp.net/threads/seedminer-single-system-dsiware-injection.495685/
(under "how can I help")

If you're still uncomfortable, you don't have to share, it's completely optional.
