### ISSUE TITLE
Full macOS Support

### ISSUE THREAD

**Issue by elaine-jackson** [zoogie/seedminer#6]
By any chance could we work on getting this script to work on macOS. Python isn't my best language (I'm used to web development not this stuff), however I'm willing to donate CPU/GPU Time and testing.

**Comment by zoogie** [comment]
I don't have a mac to test. I'm not focusing on expanding PC platforms right now, but I would accept pull requests.

**Comment by Jimmy-Z** [comment]
I do have a Mac but it's too old I rarely turns it on so... maybe someday.

**Comment by thehonkinggoose** [comment]
Welp maybe it's time for me to learn Python, let me think about it and I'll get back to you guys.

**Comment by jason0597** [comment]
btw this should be written in c/c++, bruteforcing needs every inch of speed it can get
the python script is just a frontend, the actual bruteforcing is happening behind with the c/c++ code and the opencl code. 
if you want to port it to mac, you need to work with that, not the python front end
