### ISSUE TITLE
seedminer_launcher.exe Triggering Virus Detection from Windows Defender

### ISSUE THREAD

**Issue by GhostSonic21** [zoogie/seedminer#7]
seedminer_launcher.exe From the latest "1.2" release seems to be detected by Windows Defender, may affect other scanners as well. Specifically specifies as "Trojan:Win32/Tiggre!plock" or "Trojan:Win32/Azden.B!cl"

Screenshots, mind my folder naming:
![image](https://user-images.githubusercontent.com/8278613/35900543-57d008c6-0b87-11e8-86fa-1baa29edac3e.png)

![image](https://user-images.githubusercontent.com/8278613/35900545-5e4bcc12-0b87-11e8-92d3-79467586b0d2.png)

I'm assuming this is merely some sort of false-positive, though it should be looked at regardless.

Edit: Correction, Tiggre!plock is actually being triggered by TADpole separately.

**Comment by jason0597** [comment]
i'm guessing windows thinks this mines cryptocurrency secretly or something

**Comment by GhostSonic21** [comment]
It's not that, it turns out it's Pyinstaller, which is notorious for being falsely detected by virus scanners.

The python script itself doesn't even do any of the brute-forcing.

**Comment by zoogie** [comment]
The solution to this is simple: if someone doesn't trust the exe, they can run the script - it's functionally identical.
