### ISSUE TITLE
Problem with bfcl.exe

### ISSUE THREAD

**Issue by luke9977** [zoogie/seedminer#9]
When i try to bruteforce with gpu 
tells me that the bfcl.exe file is not supported by my windows version. i have windows 7 ultimate 32 bit service pack 1, how can i do?

**Comment by zoogie** [comment]
bfcl is likely to remain 64 bit for the time being. I would suggest getting help with the brute force here:
https://gbatemp.net/threads/seedminer-fc-and-mining-help.496114/

**Comment by zoogie** [comment]
Will stay 64 bit.
